name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to EC2
      run: | #run the deployment for my ec2 instance with working tesseract (tests pass)
        ssh -o StrictHostKeyChecking=no ubuntu@34.226.150.36 << 'EOF'
          cd ~/RemindRx
          git pull origin main
          tmux kill-session -t remindrx || true
          tmux new-session -d -s remindrx 'python3 -m server.server'
          echo "✅ Tmux session restarted"  
        EOF
