name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.226.150.36 << 'EOF'
          set -e  # exit on any error

          cd ~/RemindRx
          echo "🌀 Pulling latest code..."
          git pull origin main

          echo "🔪 Killing old tmux session..."
          tmux kill-session -t remindrx || true

          echo "🚀 Starting new tmux session..."
          tmux new-session -d -s remindrx '~/RemindRx/venv/bin/gunicorn -b 0.0.0.0:8080 "server.server:create_app()"'

          echo "✅ Tmux session restarted"
          tmux ls
        EOF

