name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Or macos-latest for macOS

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Nix environment using nix-develop action
      - name: Set up Nix environment
        uses: nicknovitski/nix-develop@v1

      # Run tests with pytest inside the scanner folder
      - name: Run tests
        run: pytest scanner  # Run pytest in the scanner folder

