name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Or macos-latest for macOS

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Nix
      
      - name: Set up Nix
        uses: nicknovitski/nix-develop@v1
        run: pytest scanner 
